const o =
{
    txt_about: "Về bản thân tôi",
    txt_about1: "Đây là một sản phẩm thuộc dự án giúp đỡ học OOP một cách đơn giản và trực tiếp",
    txt_about2: "Mã nguồn:",
    txt_about3: "Người phát triển: Nguyễn Du Lịch + Nguyễn Duy Minh",
    txt_menu_myweb: "Website",
    txt_menu_QnA: "Hỏi đáp nhanh",
    txt_menu_root: "Menu chính",
    txt_Greeting: "Hi {{user_full_name}}, this is chatbot help learn OOP\nYou can ask anything about OOP here by chat directly or choose menu bellow",
    txt_Greeting_VN: "Xin chào {{user_full_name}}, đây là chatbot hỗ trợ học OOP\nBạn có thể hỏi bất cứ điều gì liên quan đến OOP ở đây bao gồm khái niệm, ví dụ, bài tập, ... bằng cách nhắn tin trực tiếp hoặc chọn menu bên dưới",
    txt_ExerciseOK: "Chắc chắn",
    txt_ExerciseContinue: "Làm tiếp",
    txt_ExerciseDoNow: "Làm ngay",
    txt_ExerciseHelpThenDoNow: "Xem hướng dẫn rồi làm",
    txt_ExerciseNQuestion: "Đề thi có %s câu hỏi",
    txt_ExerciseTime: "Thời gian làm bài: %s",
    txt_ExerciseTimeLeft: "Thời gian còn lại: %s",
    txt_ExerciseTimeAndCount: "Bạn có %s để làm bài, thời gian bắt đầu tính ngay bây giờ",
    txt_ExerciseOnTest1: "Bạn đang trong một bài thi, không thể làm bài thi khác.",
    txt_ExerciseOnTest2: "Vui lòng kết thúc bài thi hiện tại trước.",
    txt_ExerciseNext: ">",
    txt_ExercisePrevious: "<",
    txt_ExerciseSubmit: "Nộp bài",
    txt_ExerciseSubmitComfirm: "Bạn có chắc muốn nộp bài không?",
    txt_ExerciseReady: "Đã hiểu",
    txt_ExerciseChooseQuestion: "Mời chọn câu hỏi",
    txt_ExerciseQuestion: "Câu %s",
    txt_ExerciseCompleteQuestion: "Bạn đã hoàn thành %s/%s câu hỏi",
    txt_ExerciseResultQuestion: "Kết quả bài thi: %s/%s",
    txt_ExerciseResultScore: "Điểm số đạt được: %s/%s",
    txt_ExerciseResultViewInWeb: "Xem chi tiết%s",
    txt_ExerciseHelp1: "HƯỚNG DẪN LÀM BÀI THI NGAY TRÊN CHATBOT",
    txt_ExerciseHelp2: "Chọn câu hỏi hỏi bằng cách nhấn vào nút câu hỏi tương ứng.",
    txt_ExerciseHelp3: `Nhấn "%s" để nộp bài`,
    txt_ExerciseHelp4: `Nhấn "%s" chuyển sang danh sách câu hỏi trước đó và "%s" cho danh sách câu hỏi kế tiếp.`,
    txt_ExerciseHelp5: "Câu hỏi nào đã trả lời sẽ được đánh dấu bởi %s.",
    txt_ExerciseHelp6: "Chọn đáp án bằng cách chọn đúng màu so với đáp án.",
    txt_ExerciseHelp7: "Đối với câu hỏi đã được trả lời, câu trả vời trước đó sẽ được đánh dấu bởi hình vuông thay vì hình tròn",
    txt_ExerciseHelp8: "Nhấn %s để tạm thời bỏ qua câu hỏi hiện tại",
    txt_ExerciseHelp9: "Nhấn %s để quay lại danh sách các câu hỏi",
    txt_ExerciseHelp10: `Nhấn "%s" ở dưới để bắt đầu`,
    txt_ExerciseSearchText: "Bạn muốn tìm bài thi gì?",
    txt_ExerciseForceEnd: "Hết giờ làm bài, đang tính toán kết quả bài làm...",
    txt_exerciseNotFound: "Không tìm thấy bài thi liên quan",
    txt_QnA_help1: "Nhắn cho tôi một câu hỏi bất kỳ liên quan đến OOP.",
    txt_QnA_help2: "Ví dụ: OOP là gì",

    get: function (stringOrTxt: string, ...args) {
        let s = this[stringOrTxt] || stringOrTxt
        args.forEach(e => s = s.replace(/%s|%d/, () => e))
        return s
    }
}
export default o